name: xeus
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  - ninja
  - pkg-config
  # Host dependencies
  - zeromq=4.3.3
  - zeromq-static=4.3.3
  - cppzmq=4.7.1
  - xtl=0.7
  - OpenSSL=1
  - libopenssl-static=1
  - nlohmann_json
  # Test dependencies
  - doctest >= 2.4.6
  - pytest
  - jupyter_kernel_test=0.4.3
